/********************************************************************************************/
/* Authors: Mohamed Gamal, Ehab Roushdy, Mohamed abelmoteleb, and Aya Yasser                */
/* Version: V01                                                                             */
/* Date: 10/09/2023                                                                         */
/* Description: PWM driver interface                                                        */
/********************************************************************************************/

#pragma once

/*PWM Definitions*/
#define PWM0                0
#define PWM1                1


/**
 * @brief Initializes the PWM module.
 *
 * This function initializes the PWM module and configures its settings.
 * It should be called before using any other PWM-related functions.
 */
void pwm_init(void);

/**
 * @brief Sets the duty cycle for the PWM signal.
 *
 * This function sets the duty cycle for the PWM signal generated by the PWM module.
 * The duty cycle should be specified as a percentage, where 0 represents 0% duty cycle
 * and 100 represents 100% duty cycle.
 *
 * @param percent The desired duty cycle as a percentage (0-100).
 */
void pwm_set_duty_cycle(unsigned char percent);
